name       : mailspring
version    : 1.10.1
release    : 39
source     :
    - https://github.com/Foundry376/Mailspring/releases/download/1.10.1/mailspring-1.10.1-amd64.deb : 06f430fedba73e8da7598174ecc5a6a1f97bdb1ba9688daeb2590f3ad00cd1d1
homepage   : https://getmailspring.com/
license    :
    - GPL-3.0-or-later
    - Distributable # mailsync
component  : network.mail
summary    : A beautiful, fast and maintained fork of Nylas Mail by one of the original authors
description: |
    Leaving Nylas Mail? Mailspring is a new version by one of the original authors. It's faster, leaner, and shipping today! Mailspring replaces the JavaScript mailsync code in Nylas Mail with a new C++ sync engine based on Mailcore2. It uses roughly half the RAM and CPU of Nylas Mail and idles with almost zero "CPU Wakes", which translates to great battery life. A major overhaul of the package manager and dependency tree mean it launches faster too. You might not even notice it's an Electron app!
replaces   : n1
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gbm)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(xkbfile)
    - pkgconfig(xshmfence)
    - cups-devel
rundeps    :
    - gnome-keyring # is required at least until kwallet can handle libsecret.
    - libglvnd
setup      : |
    ar x $sources/mailspring-${version}-amd64.deb
    tar xf data.tar.*
install    : |
    install -dm00644 $installdir
    cp -r usr $installdir

    # Link to System Libraries
    rm $installdir/usr/share/mailspring/libEGL.so
    rm $installdir/usr/share/mailspring/libGLESv2.so
    ln -s /usr/lib64/libEGL.so $installdir/usr/share/mailspring/libEGL.so
    ln -s /usr/lib64/libGLESv2.so $installdir/usr/share/mailspring/libGLESv2.so

    # Remove the doc dir which contains the Copyright file as duplicate
    rm -rf $installdir/usr/share/doc

    # Update appdata location to metainfo
    mv $installdir/usr/share/appdata $installdir/usr/share/metainfo/

