name       : mailspring
version    : 1.7.1
release    : 26
source     :
    - https://github.com/Foundry376/Mailspring/archive/1.7.1.tar.gz : 3e55ee085cde6ada634822b2efc4d656f90bd8d481ccd5dfc100a256f866edd6
license    :
    - GPL-3.0-or-later
    - Distributable # mailsync
component  : network.mail
summary    : A beautiful, fast and maintained fork of Nylas Mail by one of the original authors
description: |
    Leaving Nylas Mail? Mailspring is a new version by one of the original authors. It's faster, leaner, and shipping today! Mailspring replaces the JavaScript mailsync code in Nylas Mail with a new C++ sync engine based on Mailcore2. It uses roughly half the RAM and CPU of Nylas Mail and idles with almost zero "CPU Wakes", which translates to great battery life. A major overhaul of the package manager and dependency tree mean it launches faster too. You might not even notice it's an Electron app!
networking : yes
replaces   : n1
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(pango)
    - pkgconfig(xkbfile)
    - pkgconfig(xtst)
    - cups-devel
    - git
    - nodejs
rundeps    :
    - gnome-keyring # is required at least until kwallet can handle libsecret.
    - libglvnd
setup      : |
    %patch -p1 < $pkgfiles/0001-linux-don-t-build-a-deb-or-rpm-please.patch
    %patch -p1 < $pkgfiles/0002-do-not-check-git-history.patch
build      : |
    npm config set unsafe-perm=true
    npm install
    npm run-script build
install    : |
    # Copy to our destination
    install -dm00755 $installdir/usr/share/mailspring
    cp -r $workdir/app/dist/mailspring-linux-x64/* $installdir/usr/share/mailspring/

    # Install binary to $PATH
    install -dm00755 $installdir/usr/bin/
    ln -sv /usr/share/mailspring/mailspring $installdir/usr/bin/mailspring

    # Install icons
    for size in 16 32 64 128 256 512; do
    install -Dm00644 $workdir/app/build/resources/linux/icons/$size.png \
      $installdir/usr/share/icons/hicolor/${size}x${size}/apps/mailspring.png
    done

    # Install desktop file
    install -Dm00644 $pkgfiles/mailspring.desktop $installdir/usr/share/applications/mailspring.desktop

    # Link to System Libraries
    rm $installdir/usr/share/mailspring/libEGL.so
    rm $installdir/usr/share/mailspring/libGLESv2.so
    ln -s /usr/lib64/libEGL.so $installdir/usr/share/mailspring/libEGL.so
    ln -s /usr/lib64/libGLESv2.so $installdir/usr/share/mailspring/libGLESv2.so
