name       : mailspring
version    : 1.4.0
release    : 13
source     :
    - https://github.com/Foundry376/Mailspring/releases/download/1.4.0/mailspring-1.4.0-amd64.deb : ed1503d36be45376d15c5ec35a2d8dab5ef8b07b318e9578ce9b5ea42c3ed528
license    :
    - GPL-3.0-or-later
    - Distributable # mailsync
component  : network.mail
summary    : A beautiful, fast and maintained fork of Nylas Mail by one of the original authors
description: |
    Leaving Nylas Mail? Mailspring is a new version by one of the original authors. It's faster, leaner, and shipping today! Mailspring replaces the JavaScript mailsync code in Nylas Mail with a new C++ sync engine based on Mailcore2. It uses roughly half the RAM and CPU of Nylas Mail and idles with almost zero "CPU Wakes", which translates to great battery life. A major overhaul of the package manager and dependency tree mean it launches faster too. You might not even notice it's an Electron app!
extract    : no
networking : yes
replaces   : n1
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(krb5)
    - pkgconfig(libsecret-1)
    - pkgconfig(xi)
    - pkgconfig(xkbfile)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
    - cups-devel
# gnome-keyring is required at least until kwallet can handle libsecret
rundeps    :
    - gnome-keyring
install    : |
    ar x $sources/mailspring-${version}-amd64.deb
    tar xf data.tar.*
    mkdir -p %installroot%
    cp -r usr %installroot%/
    cp %installroot%/usr/share/icons/hicolor/64x64/apps/mailspring.png $installdir/usr/share/pixmaps/mailspring.png
