name       : mailspring
version    : 1.10.8
release    : 46
source     :
    - https://github.com/Foundry376/Mailspring/archive/refs/tags/1.10.5.tar.gz : 76f853bfb5ad7c6cb5dcffb16be4e47c8ba2d2d27e6b192b57c6c9cd0da81b59
    # The hash comes from the first 8 characters of the git sha for the mailsync submodule
    - https://mailspring-builds.s3.amazonaws.com/mailsync/8007d5f8/linux/mailsync.tar.gz : 5e19d68737ef443d884eedf3f7e834d6db52d7111241abd7bfb3c59887fbbcf8
homepage   : https://getmailspring.com/
license    :
    - GPL-3.0-or-later
    - Distributable # mailsync
component  : network.mail
summary    : A beautiful, fast and maintained fork of Nylas Mail by one of the original authors
description: |
    Leaving Nylas Mail? Mailspring is a new version by one of the original authors. It's faster, leaner, and shipping today! Mailspring replaces the JavaScript mailsync code in Nylas Mail with a new C++ sync engine based on Mailcore2. It uses roughly half the RAM and CPU of Nylas Mail and idles with almost zero "CPU Wakes", which translates to great battery life. A major overhaul of the package manager and dependency tree mean it launches faster too. You might not even notice it's an Electron app!
networking : yes
replaces   : n1
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gbm)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(xkbfile)
    - cups-devel
    - git
    - jq
    - nodejs
setup      : |
    %patch -p1 < $pkgfiles/0001-linux-don-t-build-a-deb-or-rpm-please.patch
    %patch -p1 < $pkgfiles/0002-do-not-check-git-history.patch
    %patch -p1 < $pkgfiles/0003-Don-t-download-mailsync-binaries.patch
    %patch -p1 < $pkgfiles/0004-Disable-update-notification.patch

    tar -xf $sources/mailsync.tar.gz -C $workdir/app

    export ELECTRON_VERSION=19.1.5
    npm install electron@$ELECTRON_VERSION

    # Electron versions need to be in format "$ELECTRON_VERSION" while npm install creates entries with "^$ELECTRON_VERSION"
    tmp=$(mktemp)
    jq ".dependencies.electron = \"${ELECTRON_VERSION}\"" package.json > "$tmp" && mv "$tmp" package.json
build      : |
    npm config set unsafe-perm=true
    npm install
    npm run build
install    : |
    install -dm00755 $installdir/usr/share/mailspring
    cp -r $workdir/app/dist/mailspring-linux-x64/* $installdir/usr/share/mailspring/

    # Install binary to $PATH
    install -dm00755 $installdir/usr/bin/
    ln -sv /usr/share/mailspring/mailspring $installdir/usr/bin/mailspring

    # Install icons
    for size in 16 32 64 128 256 512; do
    install -Dm00644 $workdir/app/build/resources/linux/icons/$size.png \
        $installdir/usr/share/icons/hicolor/${size}x${size}/apps/mailspring.png
    done

    # Install desktop file
    install -Dm00644 $pkgfiles/Mailspring.desktop $installdir/usr/share/applications/Mailspring.desktop
